# basic options
title: Your awesome title
author: GitHub User
email: apk29@hotmail.com
description: Sample Blog Website
twitter_username: pirateno2
github_username:  apk29

# Build settings
markdown: kramdown
theme: minima
